# Generated by Django 2.1.3 on 2018-12-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='body',
            new_name='article_content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='photo_path',
            new_name='article_image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='abstract',
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('1', '国内新闻'), ('2', '国际新闻'), ('3', '科技'), ('4', '焦点')], max_length=1, verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
