# Generated by Django 2.1.3 on 2018-12-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181205_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='upload_path',
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
